name: CPU
version: 1.3.3
main: me.waicool20.cpu.CPUPlugin
author: waicool20
Description: Chest Processing Unit

commands:
  cpu:
    description: For more commands type "/cpu help"
  typifier:
    description: Gives players a typifier
    permission-message: §c[CPU] You do not have the permission to run this command!
    permission: cpu.typifier

permission:
  cpu.typifier:
    description: Permission to use /typifier
    default: true